title: "Computing at UCLA"
description: "Career, major, and course guides to studying the computing fields at UCLA"
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-slate
plugins:
  - jekyll-redirect-from